# Generated by Django 3.2 on 2021-08-09 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210725_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregatetype', models.CharField(max_length=255)),
                ('aggregateid', models.CharField(max_length=255)),
                ('event_type', models.CharField(db_column='type', max_length=255)),
                ('payload', models.TextField()),
            ],
        ),
    ]
