# Generated by Django 3.2 on 2021-08-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='payload',
            field=models.BinaryField(),
        ),
    ]
